
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class SignupPage extends javax.swing.JFrame {

  
    public SignupPage() {
        initComponents();
    }
      public void registerUser(String lastname, String firstname, String gender, String course, String yearLevel, String username, String password) {
        Connection conn = DatabaseConnection.getConnection();
        PreparedStatement pstmt = null;
        if (conn != null) {
            try {
                String sql = "INSERT INTO users (first_name, last_name, sex, course, year_level, username, password) VALUES (?, ?, ?, ?, ?, ?, ?)";
                pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, firstname);
                pstmt.setString(2, lastname);
                pstmt.setString(3, gender);
                pstmt.setString(4, course);
                pstmt.setString(5, yearLevel);
                pstmt.setString(6, username);
                pstmt.setString(7, password); // Corrected variable name

                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "User registered successfully!", "registered", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {} 
        } else {
            System.out.println("Failed to connect to database!");
        }
    }

    public void close(){
    WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        Lname = new javax.swing.JLabel();
        Uname = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        LnameTextField = new javax.swing.JTextField();
        UnameTextField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        MaleRbtn = new javax.swing.JRadioButton();
        FemaleRbtn = new javax.swing.JRadioButton();
        signupButton = new javax.swing.JButton();
        fname = new javax.swing.JLabel();
        fnameTextField = new javax.swing.JTextField();
        Login = new javax.swing.JLabel();
        Login1 = new javax.swing.JLabel();
        showpass = new javax.swing.JCheckBox();
        Course = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        coursecombox = new javax.swing.JComboBox<>();
        year_levelcombox = new javax.swing.JComboBox<>();
        Back = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel10.setBackground(new java.awt.Color(254, 247, 231));
        jPanel10.setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel9.setBackground(new java.awt.Color(239, 123, 82));

        Lname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Lname.setForeground(new java.awt.Color(0, 53, 82));
        Lname.setText("Last name : ");

        Uname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Uname.setForeground(new java.awt.Color(0, 53, 82));
        Uname.setText("Username :");

        password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(0, 53, 82));
        password.setText("Password :");

        sex.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sex.setForeground(new java.awt.Color(0, 53, 82));
        sex.setText("Sex :");

        LnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnameTextFieldusernameFieldActionPerformed(evt);
            }
        });

        UnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnameTextFieldjTextField3ActionPerformed(evt);
            }
        });

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        buttonGroup1.add(MaleRbtn);
        MaleRbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MaleRbtn.setForeground(new java.awt.Color(0, 53, 82));
        MaleRbtn.setText("Male");

        buttonGroup1.add(FemaleRbtn);
        FemaleRbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FemaleRbtn.setForeground(new java.awt.Color(0, 53, 82));
        FemaleRbtn.setText("Female");
        FemaleRbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleRbtnjRadioButton2ActionPerformed(evt);
            }
        });

        signupButton.setBackground(new java.awt.Color(0, 53, 82));
        signupButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        signupButton.setForeground(new java.awt.Color(254, 247, 231));
        signupButton.setText("Sign-up");
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonsignupButtonActionPerformed(evt);
            }
        });

        fname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fname.setForeground(new java.awt.Color(0, 53, 82));
        fname.setText("First name :");

        fnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameTextFieldjTextField1ActionPerformed(evt);
            }
        });

        Login.setBackground(new java.awt.Color(254, 247, 231));
        Login.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Login.setForeground(new java.awt.Color(254, 247, 231));
        Login.setText("Sign");

        Login1.setBackground(new java.awt.Color(254, 247, 231));
        Login1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Login1.setForeground(new java.awt.Color(0, 53, 82));
        Login1.setText("up");

        showpass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showpass.setForeground(new java.awt.Color(0, 53, 82));
        showpass.setText("Show password");
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });

        Course.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Course.setForeground(new java.awt.Color(0, 53, 82));
        Course.setText("Course :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 53, 82));
        jLabel2.setText("Year level :");

        coursecombox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        coursecombox.setForeground(new java.awt.Color(0, 53, 82));
        coursecombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSIT", "BSIS" }));

        year_levelcombox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        year_levelcombox.setForeground(new java.awt.Color(0, 53, 82));
        year_levelcombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st Year", "2nd Year", "3rd Year", "4th Year" }));

        Back.setBackground(new java.awt.Color(153, 153, 153));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(0, 53, 82));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Uname, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Course, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)))
                    .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lname)
                    .addComponent(fname))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PasswordField)
                    .addComponent(signupButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UnameTextField)
                    .addComponent(year_levelcombox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coursecombox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Login1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(showpass, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(MaleRbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(FemaleRbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LnameTextField)
                    .addComponent(fnameTextField))
                .addGap(47, 47, 47))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login)
                    .addComponent(Login1))
                .addGap(21, 21, 21)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Lname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaleRbtn)
                    .addComponent(FemaleRbtn)
                    .addComponent(sex))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coursecombox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Course, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year_levelcombox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Uname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showpass, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BGG.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameTextFieldjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameTextFieldjTextField1ActionPerformed

    }//GEN-LAST:event_fnameTextFieldjTextField1ActionPerformed

    private void signupButtonsignupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonsignupButtonActionPerformed


ButtonModel groupBtn = buttonGroup1.getSelection();
String firstname = fnameTextField.getText();
String lastname = LnameTextField.getText();
String course = coursecombox.getSelectedItem().toString();
String yearLevel = year_levelcombox.getSelectedItem().toString();
String username = UnameTextField.getText();
String newPassword = new String(PasswordField.getPassword());

// Validate required fields
if(groupBtn == null || newPassword.isEmpty() || firstname.isEmpty() || lastname.isEmpty() || course.isEmpty() || yearLevel.isEmpty() || username.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Please fill out all required fields.", "Error", JOptionPane.ERROR_MESSAGE);
} else {
    String gender = "";
    if (MaleRbtn.isSelected()) {
        gender = "Male";
    } else if (FemaleRbtn.isSelected()) {
        gender = "Female";
    }

    // Save to Database (with hashing inside registerUser)
    registerUser(lastname, firstname, gender, course, yearLevel, username, newPassword);
    close();
            LoginPage login = new LoginPage();
            login.setVisible(true);
            login.pack();
            login.setLocationRelativeTo(null);
}


    }//GEN-LAST:event_signupButtonsignupButtonActionPerformed
    
    private void FemaleRbtnjRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleRbtnjRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleRbtnjRadioButton2ActionPerformed

    private void UnameTextFieldjTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnameTextFieldjTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UnameTextFieldjTextField3ActionPerformed

    private void LnameTextFieldusernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnameTextFieldusernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LnameTextFieldusernameFieldActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
        if (showpass.isSelected()) {
    PasswordField.setEchoChar((char) 0);
  
} else {
    PasswordField.setEchoChar('•');

}

    }//GEN-LAST:event_showpassActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
            close();
            LoginPage login = new LoginPage();
            login.setVisible(true);
            login.pack();
            login.setLocationRelativeTo(null);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Course;
    private javax.swing.JRadioButton FemaleRbtn;
    private javax.swing.JLabel Lname;
    private javax.swing.JTextField LnameTextField;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Login1;
    private javax.swing.JRadioButton MaleRbtn;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel Uname;
    private javax.swing.JTextField UnameTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> coursecombox;
    private javax.swing.JLabel fname;
    private javax.swing.JTextField fnameTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel password;
    private javax.swing.JLabel sex;
    private javax.swing.JCheckBox showpass;
    private javax.swing.JButton signupButton;
    private javax.swing.JComboBox<String> year_levelcombox;
    // End of variables declaration//GEN-END:variables
}
